using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Brovan.Generators
{
    [Generator(LanguageNames.CSharp)]
    public sealed class StructSerializerGenerator : IIncrementalGenerator
    {
        private const int MaxNestingDepth = 8;

        private static readonly DiagnosticDescriptor UnsupportedFieldDiagnostic = new DiagnosticDescriptor(
            id: "BROVANGEN001",
            title: "Unsupported field in [GenerateStructSerializer] struct",
            messageFormat: "Field '{0}' on struct '{1}' has a shape the struct serializer generator cannot marshal",
            category: "Brovan.Generators",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor NestingTooDeepDiagnostic = new DiagnosticDescriptor(
            id: "BROVANGEN002",
            title: "Struct nesting too deep for [GenerateStructSerializer]",
            messageFormat: "Struct '{0}' nests more than {1} levels deep (possible cyclic struct reference)",
            category: "Brovan.Generators",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var structs = context.SyntaxProvider.CreateSyntaxProvider(IsStructCandidate, GetStructSymbol);
            var combined = context.CompilationProvider.Combine(structs.Collect());
            context.RegisterSourceOutput(combined, Execute);
        }

        private static bool IsStructCandidate(SyntaxNode node, CancellationToken ct)
        {
            return node is StructDeclarationSyntax s && s.AttributeLists.Count > 0;
        }

        private static INamedTypeSymbol? GetStructSymbol(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            return ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol;
        }

        private sealed class GenContext
        {
            public readonly INamedTypeSymbol? InlineAttr;
            public readonly INamedTypeSymbol? PtrAttr;
            public readonly SourceProductionContext Ctx;

            public GenContext(INamedTypeSymbol? inlineAttr, INamedTypeSymbol? ptrAttr, SourceProductionContext ctx)
            {
                InlineAttr = inlineAttr;
                PtrAttr = ptrAttr;
                Ctx = ctx;
            }
        }

        private readonly struct FieldSlot
        {
            public readonly IFieldSymbol Field;
            public readonly int Abs64;
            public readonly int Abs32;

            public FieldSlot(IFieldSymbol field, int abs64, int abs32)
            {
                Field = field;
                Abs64 = abs64;
                Abs32 = abs32;
            }
        }

        private static void Execute(SourceProductionContext ctx, (Compilation comp, ImmutableArray<INamedTypeSymbol?> structs) source)
        {
            var (compilation, structSymbols) = source;

            var markerAttr = compilation.GetTypeByMetadataName("Brovan.Core.Emulation.OS.GenerateStructSerializerAttribute");
            if (markerAttr == null)
                return;

            var inlineAttr = compilation.GetTypeByMetadataName("Brovan.Core.Emulation.OS.EmulatedInlineAttribute");
            var ptrAttr = compilation.GetTypeByMetadataName("Brovan.Core.Emulation.OS.EmulatedPointerAttribute");

            var candidates = new List<INamedTypeSymbol>();
            var seen = new HashSet<string>();

            foreach (var sym in structSymbols)
            {
                if (sym == null) continue;
                if (!seen.Add(sym.ToDisplayString())) continue;
                if (sym.GetAttributes().Any(a => SymbolEquals(a.AttributeClass, markerAttr)))
                    candidates.Add(sym);
            }

            if (candidates.Count == 0)
                return;

            var gc = new GenContext(inlineAttr, ptrAttr, ctx);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using System.Buffers;");
            sb.AppendLine("using System.Buffers.Binary;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using Brovan.Core.Helpers;");
            sb.AppendLine("using static Brovan.Core.Helpers.BinaryHelpers;");
            sb.AppendLine();
            sb.AppendLine("namespace Brovan.Core.Emulation.OS");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class StructSerializer");
            sb.AppendLine("    {");

            for (int i = 0; i < candidates.Count; i++)
            {
                var sym = candidates[i];
                string typeName = sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string safeName = sym.Name;

                GenerateGetSize(sb, gc, sym, safeName);
                GenerateWriteStruct(sb, gc, sym, typeName, safeName);
                GenerateParseStruct(sb, gc, sym, typeName, safeName);

                sb.AppendLine();
            }

            GenerateRegistration(sb, candidates);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource("StructSerializer.Generated.cs", sb.ToString());
        }

        private static void GenerateRegistration(StringBuilder sb, List<INamedTypeSymbol> candidates)
        {
            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        internal static void RegisterGeneratedStructSerializers()");
            sb.AppendLine("        {");
            foreach (var sym in candidates)
            {
                string typeName = sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string safeName = sym.Name;
                sb.AppendLine($"            RegisterDirect<{typeName}>(");
                sb.AppendLine($"                WriteStructDirect_{safeName},");
                sb.AppendLine($"                ParseStructDirect_{safeName},");
                sb.AppendLine($"                ParseStructDirect_{safeName},");
                sb.AppendLine($"                GetStructSizeDirect_{safeName},");
                sb.AppendLine($"                GetStructSizeDirect_{safeName});");
            }
            sb.AppendLine("        }");
        }

        // --- Top-level method generation ---

        private static void GenerateGetSize(StringBuilder sb, GenContext gc, INamedTypeSymbol sym, string safeName)
        {
            int size64 = ComputeSize(sym, true, gc);
            int size32 = ComputeSize(sym, false, gc);

            sb.AppendLine($"        internal static int GetStructSizeDirect_{safeName}(bool Is64) => Is64 ? {size64} : {size32};");
            sb.AppendLine($"        internal static int GetStructSizeDirect_{safeName}(BinaryEmulator Emulator) => GetStructSizeDirect_{safeName}(Emulator._binary.Architecture == BinaryArchitecture.x64);");
        }

        private static void GenerateWriteStruct(StringBuilder sb, GenContext gc, INamedTypeSymbol sym, string typeName, string safeName)
        {
            sb.AppendLine($"        internal static WriteStructResult WriteStructDirect_{safeName}(BinaryEmulator Emulator, ulong Address, {typeName} Value)");
            sb.AppendLine("        {");
            sb.AppendLine("            bool Is64 = Emulator._binary.Architecture == BinaryArchitecture.x64;");
            sb.AppendLine($"            int Size = GetStructSizeDirect_{safeName}(Is64);");
            sb.AppendLine($"            if (Size <= 0) return WriteStructResult.Fail(WriteStructError.InvalidStructLayout, \"{safeName} has zero size\");");
            sb.AppendLine("            if (!Emulator.IsRegionMapped(Address, (ulong)Size))");
            sb.AppendLine($"                return WriteStructResult.Fail(WriteStructError.DestinationNotMapped, $\"{safeName} (0x{{Size:X}} bytes) at 0x{{Address:X}} is not fully mapped\");");
            sb.AppendLine("            byte[] Buf = ArrayPool<byte>.Shared.Rent(Size);");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                Span<byte> Dst = Buf.AsSpan(0, Size);");
            sb.AppendLine("                Dst.Clear();");
            sb.AppendLine("                int Off = 0;");

            EmitFieldsWrite(sb, gc, sym, "Value", 0, 0, 0);

            sb.AppendLine("                if (!Emulator.WriteMemory(Address, Dst))");
            sb.AppendLine($"                    return WriteStructResult.Fail(WriteStructError.DestinationNotMapped, $\"WriteMemory failed for {safeName} at 0x{{Address:X}}\");");
            sb.AppendLine("                return WriteStructResult.Ok;");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { ArrayPool<byte>.Shared.Return(Buf); }");
            sb.AppendLine("        }");
        }

        private static void GenerateParseStruct(StringBuilder sb, GenContext gc, INamedTypeSymbol sym, string typeName, string safeName)
        {
            sb.AppendLine($"        internal static bool ParseStructDirect_{safeName}(BinaryEmulator Emulator, ulong Address, out {typeName} Value)");
            sb.AppendLine("        {");
            sb.AppendLine("            Value = default;");
            sb.AppendLine("            bool Is64 = Emulator._binary.Architecture == BinaryArchitecture.x64;");
            sb.AppendLine($"            int Size = GetStructSizeDirect_{safeName}(Is64);");
            sb.AppendLine("            if (Size <= 0) return false;");
            sb.AppendLine("            byte[] Buf = ArrayPool<byte>.Shared.Rent(Size);");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                Span<byte> Span = Buf.AsSpan(0, Size);");
            sb.AppendLine("                if (!Emulator.ReadMemory(Address, Span)) return false;");
            sb.AppendLine($"                return ParseStructDirect_{safeName}(Emulator, Buf, out Value);");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { ArrayPool<byte>.Shared.Return(Buf); }");
            sb.AppendLine("        }");

            sb.AppendLine($"        internal static bool ParseStructDirect_{safeName}(BinaryEmulator Emulator, byte[] Raw, out {typeName} Value)");
            sb.AppendLine("        {");
            sb.AppendLine("            Value = default;");
            sb.AppendLine("            bool Is64 = Emulator._binary.Architecture == BinaryArchitecture.x64;");
            sb.AppendLine($"            int Size = GetStructSizeDirect_{safeName}(Is64);");
            sb.AppendLine("            if (Raw == null || Raw.Length < Size) return false;");
            sb.AppendLine("            int Off = 0;");

            EmitFieldsRead(sb, gc, sym, "Value", 0, 0, 0);

            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
        }

        // --- Recursive field offset walking ---

        private static IEnumerable<FieldSlot> EnumerateFieldSlots(INamedTypeSymbol structType, int base64, int base32, GenContext gc)
        {
            bool isExplicit = IsExplicitLayout(structType);
            int local64 = 0, local32 = 0;

            foreach (var field in GetOrderedFields(structType, isExplicit))
            {
                int rel64, rel32;
                if (isExplicit)
                {
                    int off = GetExplicitFieldOffset(field);
                    rel64 = off;
                    rel32 = off;
                }
                else
                {
                    rel64 = local64;
                    rel32 = local32;
                }

                yield return new FieldSlot(field, base64 + rel64, base32 + rel32);

                if (!isExplicit)
                {
                    local64 += GetFieldSize(field, true, gc);
                    local32 += GetFieldSize(field, false, gc);
                }
            }
        }

        private static void EmitFieldsWrite(StringBuilder sb, GenContext gc, INamedTypeSymbol structType, string valuePath, int base64, int base32, int depth)
        {
            if (depth > MaxNestingDepth)
            {
                ReportNestingTooDeep(gc, structType);
                return;
            }

            foreach (var slot in EnumerateFieldSlots(structType, base64, base32, gc))
                EmitFieldWrite(sb, gc, slot.Field, $"{valuePath}.{slot.Field.Name}", slot.Abs64, slot.Abs32, depth);
        }

        private static void EmitFieldsRead(StringBuilder sb, GenContext gc, INamedTypeSymbol structType, string valuePath, int base64, int base32, int depth)
        {
            if (depth > MaxNestingDepth)
            {
                ReportNestingTooDeep(gc, structType);
                return;
            }

            foreach (var slot in EnumerateFieldSlots(structType, base64, base32, gc))
                EmitFieldRead(sb, gc, slot.Field, $"{valuePath}.{slot.Field.Name}", slot.Abs64, slot.Abs32, depth);
        }

        // --- Per-field dispatch ---

        private static void EmitOffsetAssign(StringBuilder sb, int abs64, int abs32)
        {
            sb.AppendLine(abs64 == abs32
                ? $"                Off = {abs64};"
                : $"                Off = Is64 ? {abs64} : {abs32};");
        }

        private static void EmitFieldWrite(StringBuilder sb, GenContext gc, IFieldSymbol field, string accessExpr, int abs64, int abs32, int depth)
        {
            var ft = field.Type;
            var (inlineSize, ascii, ptrContent) = GetFieldAttrs(field, gc);

            if (ft is IArrayTypeSymbol arrSym)
            {
                EmitArrayFieldWrite(sb, gc, field, arrSym, accessExpr, abs64, abs32, inlineSize, depth);
                return;
            }

            if (ft.TypeKind == TypeKind.Enum)
            {
                EmitOffsetAssign(sb, abs64, abs32);
                var underlying = ((INamedTypeSymbol)ft).EnumUnderlyingType!;
                EmitEnumLeafWrite(sb, accessExpr, underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "Off");
                return;
            }

            if (ft.SpecialType == SpecialType.System_Boolean)
            {
                EmitOffsetAssign(sb, abs64, abs32);
                sb.AppendLine($"                Dst[Off] = (byte)({accessExpr} ? 1 : 0);");
                return;
            }

            if (ft.SpecialType == SpecialType.System_String)
            {
                if (inlineSize <= 0 && ptrContent == null)
                {
                    ReportUnsupported(gc, field);
                    return;
                }
                EmitOffsetAssign(sb, abs64, abs32);
                EmitStringLeafWrite(sb, accessExpr, inlineSize, ascii, ptrContent, "Off");
                return;
            }

            if (IsNumericPrimitive(ft))
            {
                EmitOffsetAssign(sb, abs64, abs32);
                EmitPrimitiveLeafWrite(sb, accessExpr, ft.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "Off");
                return;
            }

            if (ft.IsValueType && !IsPrimitiveType(ft))
            {
                if (ptrContent?.ToString() == "Struct")
                {
                    ReportUnsupported(gc, field);
                    return;
                }
                EmitFieldsWrite(sb, gc, (INamedTypeSymbol)ft, accessExpr, abs64, abs32, depth + 1);
                return;
            }

            ReportUnsupported(gc, field);
        }

        private static void EmitFieldRead(StringBuilder sb, GenContext gc, IFieldSymbol field, string accessExpr, int abs64, int abs32, int depth)
        {
            var ft = field.Type;
            var (inlineSize, ascii, ptrContent) = GetFieldAttrs(field, gc);

            if (ft is IArrayTypeSymbol arrSym)
            {
                EmitArrayFieldRead(sb, gc, field, arrSym, accessExpr, abs64, abs32, inlineSize, depth);
                return;
            }

            if (ft.TypeKind == TypeKind.Enum)
            {
                EmitOffsetAssign(sb, abs64, abs32);
                var underlying = ((INamedTypeSymbol)ft).EnumUnderlyingType!;
                EmitEnumLeafRead(sb, accessExpr, ft.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "Off");
                return;
            }

            if (ft.SpecialType == SpecialType.System_Boolean)
            {
                EmitOffsetAssign(sb, abs64, abs32);
                sb.AppendLine($"                {accessExpr} = Raw[Off] != 0;");
                return;
            }

            if (ft.SpecialType == SpecialType.System_String)
            {
                if (inlineSize <= 0 && ptrContent == null)
                {
                    ReportUnsupported(gc, field);
                    return;
                }
                EmitOffsetAssign(sb, abs64, abs32);
                EmitStringLeafRead(sb, accessExpr, inlineSize, ascii, ptrContent, "Off");
                return;
            }

            if (IsNumericPrimitive(ft))
            {
                EmitOffsetAssign(sb, abs64, abs32);
                EmitPrimitiveLeafRead(sb, accessExpr, ft.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "Off");
                return;
            }

            if (ft.IsValueType && !IsPrimitiveType(ft))
            {
                if (ptrContent?.ToString() == "Struct")
                {
                    ReportUnsupported(gc, field);
                    return;
                }
                EmitFieldsRead(sb, gc, (INamedTypeSymbol)ft, accessExpr, abs64, abs32, depth + 1);
                return;
            }

            ReportUnsupported(gc, field);
        }

        // --- Inline arrays (byte[] pointer/inline, and inline arrays of primitives/enums/structs) ---

        private static void EmitArrayFieldWrite(StringBuilder sb, GenContext gc, IFieldSymbol field, IArrayTypeSymbol arrSym, string accessExpr, int abs64, int abs32, int inlineSize, int depth)
        {
            var elem = arrSym.ElementType;

            if (elem.SpecialType == SpecialType.System_Byte)
            {
                EmitOffsetAssign(sb, abs64, abs32);
                if (inlineSize > 0)
                {
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    byte[]? Src = {accessExpr};");
                    sb.AppendLine($"                    if (Src != null) {{ int Copy = Math.Min(Src.Length, {inlineSize}); Src.AsSpan(0, Copy).CopyTo(Dst.Slice(Off, Copy)); }}");
                    sb.AppendLine("                }");
                }
                else
                {
                    sb.AppendLine("                {");
                    sb.AppendLine("                    ulong BytePtr = 0;");
                    sb.AppendLine($"                    byte[]? RawB = {accessExpr};");
                    sb.AppendLine("                    if (RawB != null && RawB.Length > 0)");
                    sb.AppendLine("                    {");
                    sb.AppendLine("                        BytePtr = Emulator.MapUniqueAddress((ulong)RawB.Length, MemoryProtection.ReadWrite);");
                    sb.AppendLine($"                        if (BytePtr == 0) return WriteStructResult.Fail(WriteStructError.PointerAllocationFailed, \"Alloc failed for {field.Name}\");");
                    sb.AppendLine($"                        if (!Emulator.WriteMemory(BytePtr, RawB)) return WriteStructResult.Fail(WriteStructError.PointerDestinationNotMapped, \"WriteMemory failed for {field.Name}\");");
                    sb.AppendLine("                    }");
                    sb.AppendLine("                    if (Is64) BinaryPrimitives.WriteUInt64LittleEndian(Dst.Slice(Off, 8), BytePtr);");
                    sb.AppendLine("                    else BinaryPrimitives.WriteUInt32LittleEndian(Dst.Slice(Off, 4), (uint)BytePtr);");
                    sb.AppendLine("                }");
                }
                return;
            }

            if (inlineSize <= 0)
            {
                ReportUnsupported(gc, field);
                return;
            }

            int elemSize64 = GetElementTypeSize(elem, true, gc);
            int elemSize32 = GetElementTypeSize(elem, false, gc);
            if (elemSize64 <= 0 || elemSize32 <= 0)
            {
                ReportUnsupported(gc, field);
                return;
            }

            string elemTypeDisplay = elem.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            for (int i = 0; i < inlineSize; i++)
            {
                int e64 = abs64 + i * elemSize64;
                int e32 = abs32 + i * elemSize32;
                string local = $"Elem_{field.Name}_{depth}_{i}";

                sb.AppendLine($"                {elemTypeDisplay} {local} = ({accessExpr} != null && {accessExpr}.Length > {i}) ? {accessExpr}[{i}] : default;");

                if (elem.TypeKind == TypeKind.Enum)
                {
                    EmitOffsetAssign(sb, e64, e32);
                    var underlying = ((INamedTypeSymbol)elem).EnumUnderlyingType!;
                    EmitEnumLeafWrite(sb, local, underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "Off");
                }
                else if (elem.SpecialType == SpecialType.System_Boolean)
                {
                    EmitOffsetAssign(sb, e64, e32);
                    sb.AppendLine($"                Dst[Off] = (byte)({local} ? 1 : 0);");
                }
                else if (IsNumericPrimitive(elem))
                {
                    EmitOffsetAssign(sb, e64, e32);
                    EmitPrimitiveLeafWrite(sb, local, elem.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "Off");
                }
                else if (elem.IsValueType && !IsPrimitiveType(elem))
                {
                    EmitFieldsWrite(sb, gc, (INamedTypeSymbol)elem, local, e64, e32, depth + 1);
                }
                else
                {
                    ReportUnsupported(gc, field);
                }
            }
        }

        private static void EmitArrayFieldRead(StringBuilder sb, GenContext gc, IFieldSymbol field, IArrayTypeSymbol arrSym, string accessExpr, int abs64, int abs32, int inlineSize, int depth)
        {
            var elem = arrSym.ElementType;

            if (elem.SpecialType == SpecialType.System_Byte)
            {
                EmitOffsetAssign(sb, abs64, abs32);
                if (inlineSize > 0)
                {
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    byte[] Inline = new byte[{inlineSize}];");
                    sb.AppendLine($"                    Buffer.BlockCopy(Raw, Off, Inline, 0, {inlineSize});");
                    sb.AppendLine($"                    {accessExpr} = Inline;");
                    sb.AppendLine("                }");
                }
                else
                {
                    sb.AppendLine($"                {accessExpr} = null;");
                }
                return;
            }

            if (inlineSize <= 0)
            {
                ReportUnsupported(gc, field);
                return;
            }

            int elemSize64 = GetElementTypeSize(elem, true, gc);
            int elemSize32 = GetElementTypeSize(elem, false, gc);
            if (elemSize64 <= 0 || elemSize32 <= 0)
            {
                ReportUnsupported(gc, field);
                return;
            }

            string elemTypeDisplay = elem.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"                {accessExpr} = new {elemTypeDisplay}[{inlineSize}];");

            for (int i = 0; i < inlineSize; i++)
            {
                int e64 = abs64 + i * elemSize64;
                int e32 = abs32 + i * elemSize32;
                string elemAccess = $"{accessExpr}[{i}]";

                if (elem.TypeKind == TypeKind.Enum)
                {
                    EmitOffsetAssign(sb, e64, e32);
                    var underlying = ((INamedTypeSymbol)elem).EnumUnderlyingType!;
                    EmitEnumLeafRead(sb, elemAccess, elemTypeDisplay, underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "Off");
                }
                else if (elem.SpecialType == SpecialType.System_Boolean)
                {
                    EmitOffsetAssign(sb, e64, e32);
                    sb.AppendLine($"                {elemAccess} = Raw[Off] != 0;");
                }
                else if (IsNumericPrimitive(elem))
                {
                    EmitOffsetAssign(sb, e64, e32);
                    EmitPrimitiveLeafRead(sb, elemAccess, elem.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "Off");
                }
                else if (elem.IsValueType && !IsPrimitiveType(elem))
                {
                    EmitFieldsRead(sb, gc, (INamedTypeSymbol)elem, elemAccess, e64, e32, depth + 1);
                }
                else
                {
                    ReportUnsupported(gc, field);
                }
            }
        }

        // --- Leaf emitters ---

        private static void EmitPrimitiveLeafWrite(StringBuilder sb, string accessExpr, string typeDisplay, string offVar)
        {
            switch (typeDisplay)
            {
                case "byte": sb.AppendLine($"                Dst[{offVar}] = {accessExpr};"); break;
                case "sbyte": sb.AppendLine($"                Dst[{offVar}] = (byte){accessExpr};"); break;
                case "ushort": sb.AppendLine($"                BinaryPrimitives.WriteUInt16LittleEndian(Dst.Slice({offVar}, 2), {accessExpr});"); break;
                case "short": sb.AppendLine($"                BinaryPrimitives.WriteInt16LittleEndian(Dst.Slice({offVar}, 2), {accessExpr});"); break;
                case "uint": sb.AppendLine($"                BinaryPrimitives.WriteUInt32LittleEndian(Dst.Slice({offVar}, 4), {accessExpr});"); break;
                case "int": sb.AppendLine($"                BinaryPrimitives.WriteInt32LittleEndian(Dst.Slice({offVar}, 4), {accessExpr});"); break;
                case "ulong": sb.AppendLine($"                BinaryPrimitives.WriteUInt64LittleEndian(Dst.Slice({offVar}, 8), {accessExpr});"); break;
                case "long": sb.AppendLine($"                BinaryPrimitives.WriteInt64LittleEndian(Dst.Slice({offVar}, 8), {accessExpr});"); break;
                case "float": sb.AppendLine($"                BinaryPrimitives.WriteSingleLittleEndian(Dst.Slice({offVar}, 4), {accessExpr});"); break;
                case "double": sb.AppendLine($"                BinaryPrimitives.WriteDoubleLittleEndian(Dst.Slice({offVar}, 8), {accessExpr});"); break;
            }
        }

        private static void EmitPrimitiveLeafRead(StringBuilder sb, string accessExpr, string typeDisplay, string offVar)
        {
            switch (typeDisplay)
            {
                case "byte": sb.AppendLine($"                {accessExpr} = Raw[{offVar}];"); break;
                case "sbyte": sb.AppendLine($"                {accessExpr} = (sbyte)Raw[{offVar}];"); break;
                case "ushort": sb.AppendLine($"                {accessExpr} = BitConverter.ToUInt16(Raw, {offVar});"); break;
                case "short": sb.AppendLine($"                {accessExpr} = BitConverter.ToInt16(Raw, {offVar});"); break;
                case "uint": sb.AppendLine($"                {accessExpr} = BitConverter.ToUInt32(Raw, {offVar});"); break;
                case "int": sb.AppendLine($"                {accessExpr} = BitConverter.ToInt32(Raw, {offVar});"); break;
                case "ulong": sb.AppendLine($"                {accessExpr} = BitConverter.ToUInt64(Raw, {offVar});"); break;
                case "long": sb.AppendLine($"                {accessExpr} = BitConverter.ToInt64(Raw, {offVar});"); break;
                case "float": sb.AppendLine($"                {accessExpr} = BitConverter.ToSingle(Raw, {offVar});"); break;
                case "double": sb.AppendLine($"                {accessExpr} = BitConverter.ToDouble(Raw, {offVar});"); break;
            }
        }

        private static void EmitEnumLeafWrite(StringBuilder sb, string accessExpr, string underlying, string offVar)
        {
            switch (underlying)
            {
                case "byte": sb.AppendLine($"                Dst[{offVar}] = (byte){accessExpr};"); break;
                case "sbyte": sb.AppendLine($"                Dst[{offVar}] = (byte){accessExpr};"); break;
                case "ushort": sb.AppendLine($"                BinaryPrimitives.WriteUInt16LittleEndian(Dst.Slice({offVar}, 2), (ushort){accessExpr});"); break;
                case "short": sb.AppendLine($"                BinaryPrimitives.WriteInt16LittleEndian(Dst.Slice({offVar}, 2), (short){accessExpr});"); break;
                case "uint": sb.AppendLine($"                BinaryPrimitives.WriteUInt32LittleEndian(Dst.Slice({offVar}, 4), (uint){accessExpr});"); break;
                case "int": sb.AppendLine($"                BinaryPrimitives.WriteInt32LittleEndian(Dst.Slice({offVar}, 4), (int){accessExpr});"); break;
                case "ulong": sb.AppendLine($"                BinaryPrimitives.WriteUInt64LittleEndian(Dst.Slice({offVar}, 8), (ulong){accessExpr});"); break;
                case "long": sb.AppendLine($"                BinaryPrimitives.WriteInt64LittleEndian(Dst.Slice({offVar}, 8), (long){accessExpr});"); break;
            }
        }

        private static void EmitEnumLeafRead(StringBuilder sb, string accessExpr, string enumTypeDisplay, string underlying, string offVar)
        {
            switch (underlying)
            {
                case "byte": sb.AppendLine($"                {accessExpr} = ({enumTypeDisplay})Raw[{offVar}];"); break;
                case "sbyte": sb.AppendLine($"                {accessExpr} = ({enumTypeDisplay})(sbyte)Raw[{offVar}];"); break;
                case "ushort": sb.AppendLine($"                {accessExpr} = ({enumTypeDisplay})BitConverter.ToUInt16(Raw, {offVar});"); break;
                case "short": sb.AppendLine($"                {accessExpr} = ({enumTypeDisplay})BitConverter.ToInt16(Raw, {offVar});"); break;
                case "uint": sb.AppendLine($"                {accessExpr} = ({enumTypeDisplay})BitConverter.ToUInt32(Raw, {offVar});"); break;
                case "int": sb.AppendLine($"                {accessExpr} = ({enumTypeDisplay})BitConverter.ToInt32(Raw, {offVar});"); break;
                case "ulong": sb.AppendLine($"                {accessExpr} = ({enumTypeDisplay})BitConverter.ToUInt64(Raw, {offVar});"); break;
                case "long": sb.AppendLine($"                {accessExpr} = ({enumTypeDisplay})BitConverter.ToInt64(Raw, {offVar});"); break;
            }
        }

        private static void EmitStringLeafWrite(StringBuilder sb, string accessExpr, int inlineSize, bool ascii, object? ptrContent, string offVar)
        {
            if (inlineSize > 0)
            {
                string enc = ascii ? "Encoding.ASCII" : "Encoding.Unicode";
                sb.AppendLine("                {");
                sb.AppendLine($"                    string S = {accessExpr} ?? \"\";");
                sb.AppendLine($"                    byte[] Enc = {enc}.GetBytes(S);");
                sb.AppendLine($"                    int Copy = Math.Min(Enc.Length, {inlineSize});");
                sb.AppendLine($"                    Enc.AsSpan(0, Copy).CopyTo(Dst.Slice({offVar}, Copy));");
                sb.AppendLine("                }");
            }
            else if (ptrContent != null)
            {
                bool isAscii = ptrContent.ToString() == "AsciiString";
                string enc = isAscii ? "Encoding.ASCII" : "Encoding.Unicode";
                sb.AppendLine("                {");
                sb.AppendLine("                    ulong StrPtr = 0;");
                sb.AppendLine($"                    string? S = {accessExpr};");
                sb.AppendLine("                    if (S != null)");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        byte[] Enc = {enc}.GetBytes(S);");
                sb.AppendLine($"                        byte[] Full = new byte[Enc.Length + ({(isAscii ? "1" : "2")})];");
                sb.AppendLine("                        Buffer.BlockCopy(Enc, 0, Full, 0, Enc.Length);");
                sb.AppendLine("                        StrPtr = Emulator.MapUniqueAddress((ulong)Full.Length, MemoryProtection.ReadWrite);");
                sb.AppendLine("                        if (StrPtr == 0) return WriteStructResult.Fail(WriteStructError.StringAllocationFailed, \"String allocation failed\");");
                sb.AppendLine("                        if (!Emulator.WriteMemory(StrPtr, Full)) return WriteStructResult.Fail(WriteStructError.PointerDestinationNotMapped, \"WriteMemory failed for string field\");");
                sb.AppendLine("                    }");
                sb.AppendLine($"                    if (Is64) BinaryPrimitives.WriteUInt64LittleEndian(Dst.Slice({offVar}, 8), StrPtr);");
                sb.AppendLine($"                    else BinaryPrimitives.WriteUInt32LittleEndian(Dst.Slice({offVar}, 4), (uint)StrPtr);");
                sb.AppendLine("                }");
            }
        }

        private static void EmitStringLeafRead(StringBuilder sb, string accessExpr, int inlineSize, bool ascii, object? ptrContent, string offVar)
        {
            if (inlineSize > 0)
            {
                string enc = ascii ? "Encoding.ASCII" : "Encoding.Unicode";
                int step = ascii ? 1 : 2;
                string trailingCheck = step == 2 ? $" && Raw[{offVar} + Len - 1] == 0" : "";
                sb.AppendLine("                {");
                sb.AppendLine($"                    int Len = {inlineSize};");
                sb.AppendLine($"                    while (Len >= {step} && Raw[{offVar} + Len - {step}] == 0{trailingCheck}) Len -= {step};");
                sb.AppendLine($"                    {accessExpr} = {enc}.GetString(Raw, {offVar}, Len);");
                sb.AppendLine("                }");
            }
            else if (ptrContent != null)
            {
                bool isAscii = ptrContent.ToString() == "AsciiString";
                string enc = isAscii ? "Encoding.ASCII" : "Encoding.Unicode";
                sb.AppendLine("                {");
                sb.AppendLine($"                    ulong StrP = Is64 ? BitConverter.ToUInt64(Raw, {offVar}) : BitConverter.ToUInt32(Raw, {offVar});");
                sb.AppendLine($"                    {accessExpr} = StrP != 0 ? ReadNullTerminatedString(Emulator, StrP, {enc}) : null;");
                sb.AppendLine("                }");
            }
        }

        // --- Diagnostics ---

        private static void ReportUnsupported(GenContext gc, IFieldSymbol field)
        {
            var loc = field.Locations.FirstOrDefault() ?? Location.None;
            gc.Ctx.ReportDiagnostic(Diagnostic.Create(UnsupportedFieldDiagnostic, loc, field.Name, field.ContainingType?.Name ?? "?"));
        }

        private static void ReportNestingTooDeep(GenContext gc, INamedTypeSymbol structType)
        {
            var loc = structType.Locations.FirstOrDefault() ?? Location.None;
            gc.Ctx.ReportDiagnostic(Diagnostic.Create(NestingTooDeepDiagnostic, loc, structType.Name, MaxNestingDepth));
        }

        // --- Layout / size helpers ---

        private static bool IsExplicitLayout(INamedTypeSymbol sym)
        {
            // TypedConstant.Value for an enum-typed constructor argument is the boxed underlying
            // integral value (e.g. 2), not the LayoutKind member itself -- compare against the int.
            return sym.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == "System.Runtime.InteropServices.StructLayoutAttribute" &&
                a.ConstructorArguments.Length > 0 &&
                a.ConstructorArguments[0].Value is int layoutKindValue &&
                layoutKindValue == (int)LayoutKind.Explicit);
        }

        private static int GetDeclaredStructLayoutSize(INamedTypeSymbol sym)
        {
            var attr = sym.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "System.Runtime.InteropServices.StructLayoutAttribute");
            if (attr == null) return 0;

            foreach (var na in attr.NamedArguments)
                if (na.Key == "Size" && na.Value.Value is int sizeVal)
                    return sizeVal;

            return 0;
        }

        private static IEnumerable<IFieldSymbol> GetOrderedFields(INamedTypeSymbol sym, bool isExplicit)
        {
            var fields = sym.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic).ToList();
            if (isExplicit)
                fields = fields.OrderBy(GetExplicitFieldOffset).ToList();
            return fields;
        }

        private static int GetExplicitFieldOffset(IFieldSymbol field)
        {
            var attr = field.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "FieldOffsetAttribute");
            return attr != null ? (int)attr.ConstructorArguments[0].Value! : 0;
        }

        private static (int inlineSize, bool ascii, object? ptrContent) GetFieldAttrs(IFieldSymbol field, GenContext gc)
        {
            int inlineSize = 0;
            bool ascii = false;
            object? ptrContent = null;

            foreach (var attr in field.GetAttributes())
            {
                if (SymbolEquals(attr.AttributeClass, gc.InlineAttr) && attr.ConstructorArguments.Length > 0)
                {
                    inlineSize = (int)attr.ConstructorArguments[0].Value!;
                    foreach (var na in attr.NamedArguments)
                        if (na.Key == "Ascii" && na.Value.Value is bool b)
                            ascii = b;
                }
                if (SymbolEquals(attr.AttributeClass, gc.PtrAttr) && attr.ConstructorArguments.Length > 0)
                {
                    ptrContent = attr.ConstructorArguments[0].Value;
                }
            }

            return (inlineSize, ascii, ptrContent);
        }

        private static int ComputeSize(INamedTypeSymbol sym, bool is64, GenContext gc)
        {
            bool isExplicit = IsExplicitLayout(sym);
            int max = 0;
            int runningTotal = 0;

            foreach (var field in GetOrderedFields(sym, isExplicit))
            {
                int sz = GetFieldSize(field, is64, gc);
                if (isExplicit)
                    max = Math.Max(max, GetExplicitFieldOffset(field) + sz);
                else
                    runningTotal += sz;
            }

            int computed = isExplicit ? max : runningTotal;
            int declared = GetDeclaredStructLayoutSize(sym);
            return Math.Max(computed, declared);
        }

        private static int GetFieldSize(IFieldSymbol field, bool is64, GenContext gc)
        {
            var (inlineSize, _, _) = GetFieldAttrs(field, gc);
            var ft = field.Type;

            if (ft is IArrayTypeSymbol arrType)
            {
                if (arrType.ElementType.SpecialType == SpecialType.System_Byte)
                    return inlineSize > 0 ? inlineSize : (is64 ? 8 : 4);

                if (inlineSize <= 0)
                    return is64 ? 8 : 4;

                return GetElementTypeSize(arrType.ElementType, is64, gc) * inlineSize;
            }

            if (ft.TypeKind == TypeKind.Enum)
                ft = ((INamedTypeSymbol)ft).EnumUnderlyingType!;

            switch (ft.SpecialType)
            {
                case SpecialType.System_Boolean: return 1;
                case SpecialType.System_Byte: return 1;
                case SpecialType.System_SByte: return 1;
                case SpecialType.System_Int16: return 2;
                case SpecialType.System_UInt16: return 2;
                case SpecialType.System_Int32: return 4;
                case SpecialType.System_UInt32: return 4;
                case SpecialType.System_Int64: return 8;
                case SpecialType.System_UInt64: return 8;
                case SpecialType.System_Single: return 4;
                case SpecialType.System_Double: return 8;
                case SpecialType.System_String: return inlineSize > 0 ? inlineSize : (is64 ? 8 : 4);
            }

            if (ft.IsValueType && !IsPrimitiveType(ft))
                return ComputeSize((INamedTypeSymbol)ft, is64, gc);

            return 0;
        }

        private static int GetElementTypeSize(ITypeSymbol elemType, bool is64, GenContext gc)
        {
            var ft = elemType;
            if (ft.TypeKind == TypeKind.Enum)
                ft = ((INamedTypeSymbol)ft).EnumUnderlyingType!;

            switch (ft.SpecialType)
            {
                case SpecialType.System_Boolean: return 1;
                case SpecialType.System_Byte: return 1;
                case SpecialType.System_SByte: return 1;
                case SpecialType.System_Int16: return 2;
                case SpecialType.System_UInt16: return 2;
                case SpecialType.System_Int32: return 4;
                case SpecialType.System_UInt32: return 4;
                case SpecialType.System_Int64: return 8;
                case SpecialType.System_UInt64: return 8;
                case SpecialType.System_Single: return 4;
                case SpecialType.System_Double: return 8;
            }

            if (ft.IsValueType && !IsPrimitiveType(ft))
                return ComputeSize((INamedTypeSymbol)ft, is64, gc);

            return 0;
        }

        private static bool IsNumericPrimitive(ITypeSymbol t)
        {
            switch (t.SpecialType)
            {
                case SpecialType.System_Byte:
                case SpecialType.System_SByte:
                case SpecialType.System_Int16:
                case SpecialType.System_UInt16:
                case SpecialType.System_Int32:
                case SpecialType.System_UInt32:
                case SpecialType.System_Int64:
                case SpecialType.System_UInt64:
                case SpecialType.System_Single:
                case SpecialType.System_Double:
                    return true;
                default:
                    return false;
            }
        }

        private static bool IsPrimitiveType(ITypeSymbol t)
        {
            switch (t.SpecialType)
            {
                case SpecialType.System_Boolean:
                case SpecialType.System_Byte:
                case SpecialType.System_SByte:
                case SpecialType.System_Int16:
                case SpecialType.System_UInt16:
                case SpecialType.System_Int32:
                case SpecialType.System_UInt32:
                case SpecialType.System_Int64:
                case SpecialType.System_UInt64:
                case SpecialType.System_Single:
                case SpecialType.System_Double:
                    return true;
                default:
                    return false;
            }
        }

        private static bool SymbolEquals(ISymbol? a, ISymbol? b)
        {
            if (a == null || b == null) return false;
            return SymbolEqualityComparer.Default.Equals(a, b);
        }
    }
}
